### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by SingularitySurfer** [quartiq/thermostat-mqtt#1]
# ToDo list for thermostat-mqtt

- [ ] proper telemetry task with variable rate
- [ ] changeable sampling rate
- [ ] changeable adc filters
- [ ] sensible min/max currents/voltages
- [ ] PID to IIR settings update infrastructure
- [ ] general code cleanup
